services:
  - type: web
    name: laravel-backend
    env: php
    buildCommand: |
      composer install
    startCommand: |
      php artisan migrate --force && php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: PHP_EXTENSIONS
        value: pgsql pdo_pgsql
